Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/2/2020
Var
// Seção de Declarações das variáveis 

   nota01,nota02:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


   
   se ( nota01 = nota02) entao
      escreval("nota01 é diferente")
   entao
      escreval("nota01 é igual")
      
   fimse


Fimalgoritmo